# Generated by Django 5.2.8 on 2026-01-28 01:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=50, verbose_name='阶段名称')),
                ('progress_percentage', models.PositiveIntegerField(help_text='0-100', verbose_name='进度百分比')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='排序索引')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '项目阶段配置',
                'verbose_name_plural': '项目阶段配置',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目代号')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('sla_hours', models.PositiveIntegerField(blank=True, help_text='项目级 SLA 提醒窗口（小时）', null=True, verbose_name='SLA时限(小时)')),
                ('overall_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='总体进度(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('managers', models.ManyToManyField(blank=True, related_name='projects_managed', to=settings.AUTH_USER_MODEL, verbose_name='项目经理')),
                ('members', models.ManyToManyField(blank=True, related_name='projects_membership', to=settings.AUTH_USER_MODEL, verbose_name='项目成员')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_owned', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('current_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectphaseconfig', verbose_name='当前阶段')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_attachments/', verbose_name='文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project', verbose_name='项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '项目附件',
                'verbose_name_plural': '项目附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhaseChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_phase_logs', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_logs', to='projects.project', verbose_name='项目')),
                ('new_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_as_new', to='projects.projectphaseconfig', verbose_name='新阶段')),
                ('old_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_as_old', to='projects.projectphaseconfig', verbose_name='原阶段')),
            ],
            options={
                'verbose_name': '项目阶段变更日志',
                'verbose_name_plural': '项目阶段变更日志',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], help_text='为空则对项目内全部角色生效', max_length=10, null=True, verbose_name='角色')),
                ('cutoff_time', models.TimeField(default=datetime.time(20, 0), verbose_name='截止时间')),
                ('channel', models.CharField(default='email', max_length=50, verbose_name='通知渠道')),
                ('weekdays_only', models.BooleanField(default=True, verbose_name='仅工作日')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '提醒规则',
                'verbose_name_plural': '提醒规则',
                'ordering': ['project', 'role', 'cutoff_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(blank=True, default=list, help_text="权限列表，如 ['view_tasks', 'manage_tasks']", verbose_name='权限列表')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_permissions', to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员权限',
                'verbose_name_plural': '项目成员权限',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='projects_pr_is_acti_f7dee7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='projects_pr_code_80abae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reminderrule',
            unique_together={('project', 'role')},
        ),
    ]
