# Generated by Django 5.2.8 on 2026-01-28 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.DeleteModel(
            name='ReminderRule',
        ),
    ]
