# Generated by Django 5.2.8 on 2026-02-15 04:08

import core.services.storage.router
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(storage=core.services.storage.router.RouterStorage(biz_type='project_attachment'), upload_to='project_attachments/', verbose_name='文件'),
        ),
    ]
