# Generated by Django 5.2.8 on 2026-01-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_permission_role_rolepermission_role_permissions_and_more'),
        ('projects', '0002_alter_project_managers_alter_project_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_note',
            field=models.TextField(blank=True, verbose_name='进度备注'),
        ),
        migrations.AddField(
            model_name='projectphasechangelog',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='变更详情'),
        ),
        migrations.AddField(
            model_name='projectphasechangelog',
            name='new_progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='新进度'),
        ),
        migrations.AddField(
            model_name='projectphasechangelog',
            name='old_progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='原进度'),
        ),
        migrations.AddField(
            model_name='projectphaseconfig',
            name='related_role',
            field=models.ForeignKey(blank=True, help_text='该阶段的主要负责人角色（如开发、测试）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role', verbose_name='关联角色'),
        ),
    ]
