# Generated by Django 5.2.8 on 2026-02-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('url', models.URLField(verbose_name='仓库地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目仓库',
                'verbose_name_plural': '项目仓库',
                'ordering': ['created_at'],
            },
        ),
    ]
