# Generated by Django 5.2.8 on 2026-03-01 08:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectrepository'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='projects_pr_name_e0a39f_idx'),
        ),
    ]
