# Generated by Django 5.2.8 on 2026-01-30 17:49

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., project.view', max_length=100, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('group', models.CharField(blank=True, help_text='e.g., project, task', max_length=50, verbose_name='权限分组')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RBAC权限',
                'verbose_name_plural': 'RBAC权限',
                'ordering': ['group', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='键')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='值')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=50, verbose_name='导出类型')),
                ('status', models.CharField(choices=[('pending', '待处理 / Pending'), ('running', '处理中 / Running'), ('done', '完成 / Done'), ('failed', '失败 / Failed')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(default=core.models.default_export_expiry, verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '导出任务',
                'verbose_name_plural': '导出任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, verbose_name='角色')),
                ('permission', models.CharField(choices=[('view_project', '查看项目'), ('edit_project', '编辑项目'), ('delete_project', '删除项目'), ('manage_members', '管理成员'), ('view_reports', '查看报表'), ('manage_tasks', '管理任务'), ('view_tasks', '查看任务'), ('manage_phases', '管理阶段')], max_length=50, verbose_name='权限标识')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限矩阵',
                'verbose_name_plural': '权限矩阵',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], default='dev', max_length=10, verbose_name='职位')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., project_manager', max_length=100, unique=True, verbose_name='角色代码')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, help_text='系统角色不可删除', verbose_name='系统角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.role', verbose_name='父角色')),
            ],
            options={
                'verbose_name': 'RBAC角色',
                'verbose_name_plural': 'RBAC角色',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'verbose_name': 'RBAC角色权限关联',
                'verbose_name_plural': 'RBAC角色权限关联',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='core.RolePermission', to='core.permission', verbose_name='权限集合'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='偏好数据')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('task_assigned', '任务分配'), ('task_updated', '任务更新'), ('task_mention', '任务提及'), ('sla_reminder', 'SLA提醒'), ('project_update', '项目更新'), ('report_reminder', '日报提醒')], max_length=20, verbose_name='类型')),
                ('priority', models.CharField(choices=[('high', '高 / High'), ('normal', '普通 / Normal'), ('low', '低 / Low')], default='normal', max_length=10, verbose_name='优先级')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_pushed', models.BooleanField(default=False, verbose_name='是否已推送')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'), models.Index(fields=['priority'], name='core_notifi_priorit_8208cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, help_text='格式: resource_type:id，为空表示全局', max_length=100, null=True, verbose_name='资源范围')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RBAC用户角色',
                'verbose_name_plural': 'RBAC用户角色',
                'indexes': [models.Index(fields=['user', 'scope'], name='core_userro_user_id_313f9e_idx'), models.Index(fields=['scope'], name='core_userro_scope_c74f12_idx')],
                'unique_together': {('user', 'role', 'scope')},
            },
        ),
    ]
