# Generated by Django 5.2.8 on 2026-02-02 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='报表类型')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='结果数据')),
                ('status', models.CharField(choices=[('pending', '待处理 / Pending'), ('running', '处理中 / Running'), ('done', '完成 / Done'), ('failed', '失败 / Failed')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '报表任务',
                'verbose_name_plural': '报表任务',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'report_type', 'created_at'], name='core_report_user_id_f31672_idx')],
            },
        ),
    ]
