# Generated by Django 5.2.8 on 2026-02-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reportjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportJob',
        ),
    ]
