# Generated by Django 5.2.8 on 2026-01-30 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exportjob_user_alter_notification_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('high', '高 / High'), ('normal', '普通 / Normal'), ('low', '低 / Low')], default='normal', max_length=10, verbose_name='优先级'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='core_notifi_priorit_8208cb_idx'),
        ),
    ]
