# Generated by Django 5.2.8 on 2026-02-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chunkedupload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='邀请码')),
                ('email', models.EmailField(blank=True, help_text='可选，指定特定邮箱 / Optional, specific email', max_length=254, null=True, verbose_name='受邀邮箱')),
                ('status', models.CharField(choices=[('unused', '未使用 / Unused'), ('used', '已使用 / Used'), ('expired', '已过期 / Expired')], default='unused', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_invitations', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('registered_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_used', to=settings.AUTH_USER_MODEL, verbose_name='注册用户')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
                'ordering': ['-created_at'],
            },
        ),
    ]
