# Generated by Django 5.2.8 on 2026-02-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contracts/%Y/%m/', verbose_name='合同文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '劳动合同',
                'verbose_name_plural': '劳动合同',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_probation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原试用薪资')),
                ('new_probation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='新试用薪资')),
                ('old_official', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原正式薪资')),
                ('new_official', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='新正式薪资')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='货币')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '薪资历史',
                'verbose_name_plural': '薪资历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
