# Generated by Django 5.2.8 on 2026-01-30 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., project.view', max_length=100, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('group', models.CharField(blank=True, help_text='e.g., project, task', max_length=50, verbose_name='权限分组')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RBAC权限',
                'verbose_name_plural': 'RBAC权限',
                'ordering': ['group', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., project_manager', max_length=100, unique=True, verbose_name='角色代码')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, help_text='系统角色不可删除', verbose_name='系统角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.role', verbose_name='父角色')),
            ],
            options={
                'verbose_name': 'RBAC角色',
                'verbose_name_plural': 'RBAC角色',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'verbose_name': 'RBAC角色权限关联',
                'verbose_name_plural': 'RBAC角色权限关联',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='core.RolePermission', to='core.permission', verbose_name='权限集合'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, help_text='格式: resource_type:id，为空表示全局', max_length=100, null=True, verbose_name='资源范围')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RBAC用户角色',
                'verbose_name_plural': 'RBAC用户角色',
                'indexes': [models.Index(fields=['user', 'scope'], name='core_userro_user_id_313f9e_idx'), models.Index(fields=['scope'], name='core_userro_scope_c74f12_idx')],
                'unique_together': {('user', 'role', 'scope')},
            },
        ),
    ]
