# Generated by Django 5.2.8 on 2026-02-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_reportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('active', '在职'), ('terminated', '离职')], default='active', max_length=20, verbose_name='是否在职'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='入职时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hr_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='profile',
            name='official_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='正式薪资'),
        ),
        migrations.AddField(
            model_name='profile',
            name='probation_months',
            field=models.PositiveIntegerField(default=3, verbose_name='试用时长(月)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='probation_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='试用薪资'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='离职时间'),
        ),
    ]
