# Generated by Django 5.2.8 on 2026-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contract_salaryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='现住址'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='银行账号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='开户行'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='紧急联系电话'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='身份证/护照号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='联系电话'),
        ),
    ]
