# Generated by Django 5.2.8 on 2026-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_address_profile_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_card_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='usdt_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USDT 地址'),
        ),
        migrations.AddField(
            model_name='profile',
            name='usdt_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/%Y/%m/', verbose_name='USDT 收款二维码'),
        ),
    ]
