# Generated by Django 5.2.8 on 2026-02-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_department_profile_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_currency',
            field=models.CharField(choices=[('CNY', 'CNY'), ('USDT', 'USDT')], default='CNY', max_length=10, verbose_name='货币单位'),
        ),
    ]
