# Generated by Django 5.2.8 on 2026-02-05 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_department_remove_profile_employee_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intermediary_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='中介公司'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intermediary_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='中介费用'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intermediary_fee_currency',
            field=models.CharField(choices=[('CNY', 'CNY'), ('USDT', 'USDT')], default='CNY', max_length=10, verbose_name='中介费用货币单位'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['intermediary_company', 'intermediary_fee_currency'], name='idx_intermediary'),
        ),
    ]
