# Generated by Django 5.2.8 on 2026-03-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_address_remove_profile_bank_account_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['position'], name='core_profile_positio_idx'),
        ),
    ]
