# Generated by Django 5.2.8 on 2026-06-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, help_text='可选，指定特定邮箱', max_length=254, null=True, verbose_name='受邀邮箱'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(help_text='例如：project.view', max_length=100, unique=True, verbose_name='权限代码'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.CharField(blank=True, help_text='例如：project, task', max_length=50, verbose_name='权限分组'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='例如：project_manager', max_length=100, unique=True, verbose_name='角色代码'),
        ),
    ]
