# Generated by Django 5.2.8 on 2026-06-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_invitation_email_alter_permission_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', '任务分配'), ('task_updated', '任务更新'), ('task_mention', '任务提及'), ('task_collaborator', '任务协作人变更'), ('sla_reminder', 'SLA 提醒'), ('project_update', '项目更新'), ('project_assignment', '项目负责人任命'), ('project_member_change', '项目成员变更'), ('project_manager_change', '项目管理员变更'), ('report_reminder', '日报提醒'), ('system', '系统通知')], max_length=32, verbose_name='类型'),
        ),
    ]
