# Generated by Django 5.2.8 on 2026-06-20 04:14

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PROFILE_FIELDS = {
    'hr_note': 'hr_note_secure',
    'intermediary_fee_amount': 'intermediary_fee_amount_secure',
    'official_salary': 'official_salary_secure',
    'probation_salary': 'probation_salary_secure',
    'usdt_address': 'usdt_address_secure',
}
SALARY_HISTORY_FIELDS = {
    'new_official': 'new_official_secure',
    'new_probation': 'new_probation_secure',
    'old_official': 'old_official_secure',
    'old_probation': 'old_probation_secure',
}


def encrypt_sensitive_fields(apps, schema_editor):
    _copy_fields(apps, schema_editor, 'Profile', PROFILE_FIELDS, reverse=False)
    _copy_fields(apps, schema_editor, 'SalaryHistory', SALARY_HISTORY_FIELDS, reverse=False)


def restore_plaintext_fields(apps, schema_editor):
    _copy_fields(apps, schema_editor, 'Profile', PROFILE_FIELDS, reverse=True)
    _copy_fields(apps, schema_editor, 'SalaryHistory', SALARY_HISTORY_FIELDS, reverse=True)


def _copy_fields(apps, schema_editor, model_name, field_mapping, reverse):
    Model = apps.get_model('core', model_name)
    manager = Model.objects.using(schema_editor.connection.alias)
    source_to_target = (
        {secure: plain for plain, secure in field_mapping.items()}
        if reverse else field_mapping
    )
    batch = []
    for instance in manager.all().iterator(chunk_size=500):
        for source, target in source_to_target.items():
            setattr(instance, target, getattr(instance, source))
        batch.append(instance)
        if len(batch) == 500:
            manager.bulk_update(batch, list(source_to_target.values()), batch_size=500)
            batch = []
    if batch:
        manager.bulk_update(batch, list(source_to_target.values()), batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hr_note_secure',
            field=core.fields.EncryptedTextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intermediary_fee_amount_secure',
            field=core.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='中介费用'),
        ),
        migrations.AddField(
            model_name='profile',
            name='official_salary_secure',
            field=core.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='正式薪资'),
        ),
        migrations.AddField(
            model_name='profile',
            name='probation_salary_secure',
            field=core.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='试用薪资'),
        ),
        migrations.AddField(
            model_name='profile',
            name='usdt_address_secure',
            field=core.fields.EncryptedTextField(blank=True, null=True, verbose_name='USDT 地址'),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='new_official_secure',
            field=core.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='新正式薪资'),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='new_probation_secure',
            field=core.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='新试用薪资'),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='old_official_secure',
            field=core.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原正式薪资'),
        ),
        migrations.AddField(
            model_name='salaryhistory',
            name='old_probation_secure',
            field=core.fields.EncryptedDecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原试用薪资'),
        ),
        migrations.RunPython(encrypt_sensitive_fields, restore_plaintext_fields),
        migrations.RemoveField(
            model_name='profile',
            name='hr_note',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intermediary_fee_amount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='official_salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='probation_salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usdt_address',
        ),
        migrations.RemoveField(
            model_name='salaryhistory',
            name='new_official',
        ),
        migrations.RemoveField(
            model_name='salaryhistory',
            name='new_probation',
        ),
        migrations.RemoveField(
            model_name='salaryhistory',
            name='old_official',
        ),
        migrations.RemoveField(
            model_name='salaryhistory',
            name='old_probation',
        ),
        migrations.AddField(
            model_name='notification',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='幂等键'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='unique_user_notification_idempotency_key'),
        ),
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=255)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA 恢复码',
                'verbose_name_plural': 'MFA 恢复码',
                'indexes': [models.Index(fields=['user', 'used_at'], name='core_mfarec_user_id_ac1a5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('websocket', 'WebSocket'), ('email', 'Email')], max_length=16, verbose_name='渠道')),
                ('status', models.CharField(choices=[('pending', '待投递'), ('processing', '投递中'), ('sent', '已投递'), ('failed', '待重试'), ('dead', '终止重试')], default='pending', max_length=16, verbose_name='状态')),
                ('payload', models.JSONField(default=dict, verbose_name='投递负载')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='投递时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.notification', verbose_name='通知')),
            ],
            options={
                'verbose_name': '通知投递',
                'verbose_name_plural': '通知投递',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='core_notifi_status_4b71f2_idx'), models.Index(fields=['updated_at'], name='core_notifi_updated_34ad23_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'channel'), name='unique_notification_delivery_channel')],
            },
        ),
    ]
