# Generated by Django 5.2.8 on 2026-06-20 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    schema_editor.execute("""
        CREATE INDEX IF NOT EXISTS core_searchindex_fts_idx
        ON core_searchindex
        USING gin (
            (
                setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
                setweight(to_tsvector('simple', coalesce(subtitle, '')), 'B') ||
                setweight(to_tsvector('simple', coalesce(body, '')), 'C')
            )
        )
    """)
    schema_editor.execute("""
        CREATE INDEX IF NOT EXISTS core_searchindex_search_text_trgm_idx
        ON core_searchindex
        USING gin (search_text gin_trgm_ops)
    """)


def drop_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("DROP INDEX IF EXISTS core_searchindex_search_text_trgm_idx")
    schema_editor.execute("DROP INDEX IF EXISTS core_searchindex_fts_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_profile_hr_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('project', '项目'), ('task', '任务'), ('daily_report', '日报')], max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('search_text', models.TextField(blank=True)),
                ('project_ids', models.JSONField(blank=True, default=list)),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '搜索索引',
                'verbose_name_plural': '搜索索引',
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='core_search_object__a6489c_idx'), models.Index(fields=['object_type', 'updated_at'], name='core_search_object__4be447_idx'), models.Index(fields=['user_id'], name='core_search_user_id_e03f01_idx')],
                'constraints': [models.UniqueConstraint(fields=('object_type', 'object_id'), name='unique_search_index_object')],
            },
        ),
        migrations.CreateModel(
            name='DirectUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('upload_type', models.CharField(choices=[('project', '项目附件'), ('task', '任务附件'), ('avatar', '头像'), ('default', '通用')], default='default', max_length=20)),
                ('biz_type', models.CharField(default='default', max_length=50)),
                ('storage_path', models.CharField(max_length=512, unique=True)),
                ('status', models.CharField(choices=[('pending', '等待直传'), ('complete', '已校验'), ('attached', '已绑定'), ('failed', '失败')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '直传会话',
                'verbose_name_plural': '直传会话',
                'indexes': [models.Index(fields=['user', 'status'], name='core_direct_user_id_750997_idx'), models.Index(fields=['expires_at'], name='core_direct_expires_8de923_idx'), models.Index(fields=['biz_type', 'status'], name='core_direct_biz_typ_52a9dc_idx')],
            },
        ),
        migrations.RunPython(create_postgres_search_indexes, drop_postgres_search_indexes),
    ]
