# Generated by Django 5.2.8 on 2026-02-14 11:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, unique=True, verbose_name='角色')),
                ('hint', models.TextField(blank=True, verbose_name='提示语')),
                ('placeholders', models.JSONField(blank=True, default=dict, verbose_name='占位符配置')),
                ('sample_md', models.TextField(blank=True, help_text='示例 Markdown，填写页可一键套用', verbose_name='示例内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色模板',
                'verbose_name_plural': '角色模板',
                'ordering': ['sort_order', 'role'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('role', models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, verbose_name='角色')),
                ('project', models.CharField(blank=True, max_length=200, verbose_name='主项目(旧)')),
                ('status', models.CharField(choices=[('draft', '草稿 / Draft'), ('submitted', '已提交 / Submitted')], default='submitted', max_length=20, verbose_name='状态')),
                ('today_work', models.TextField(blank=True, verbose_name='今日工作')),
                ('progress_issues', models.TextField(blank=True, verbose_name='进度与问题')),
                ('tomorrow_plan', models.TextField(blank=True, verbose_name='明日计划')),
                ('testing_scope', models.TextField(blank=True, verbose_name='测试范围')),
                ('testing_progress', models.TextField(blank=True, verbose_name='测试进度')),
                ('bug_summary', models.TextField(blank=True, verbose_name='缺陷汇总')),
                ('testing_tomorrow', models.TextField(blank=True, verbose_name='明日测试计划')),
                ('product_today', models.TextField(blank=True, verbose_name='今日产品工作')),
                ('product_coordination', models.TextField(blank=True, verbose_name='协调事项')),
                ('product_tomorrow', models.TextField(blank=True, verbose_name='明日产品计划')),
                ('ui_today', models.TextField(blank=True, verbose_name='今日设计工作')),
                ('ui_feedback', models.TextField(blank=True, verbose_name='反馈修改')),
                ('ui_tomorrow', models.TextField(blank=True, verbose_name='明日设计计划')),
                ('ops_today', models.TextField(blank=True, verbose_name='今日运维工作')),
                ('ops_monitoring', models.TextField(blank=True, verbose_name='监控状况')),
                ('ops_tomorrow', models.TextField(blank=True, verbose_name='明日运维计划')),
                ('mgr_progress', models.TextField(blank=True, verbose_name='整体进度')),
                ('mgr_risks', models.TextField(blank=True, verbose_name='风险管理')),
                ('mgr_tomorrow', models.TextField(blank=True, verbose_name='明日管理计划')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('projects', models.ManyToManyField(blank=True, related_name='reports', to='projects.project', verbose_name='关联项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '日报',
                'verbose_name_plural': '日报',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='work_logs_d_user_id_148e55_idx'), models.Index(fields=['date'], name='work_logs_d_date_73f38b_idx'), models.Index(fields=['user', 'status'], name='work_logs_d_user_id_1ddf80_idx'), models.Index(fields=['role', 'date'], name='work_logs_d_role_e3c642_idx'), models.Index(fields=['status'], name='work_logs_d_status_52d8ee_idx')],
                'unique_together': {('user', 'date', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], help_text='为空则对项目内全部角色生效', max_length=10, null=True, verbose_name='角色')),
                ('cutoff_time', models.TimeField(default=datetime.time(20, 0), verbose_name='截止时间')),
                ('channel', models.CharField(default='email', max_length=50, verbose_name='通知渠道')),
                ('weekdays_only', models.BooleanField(default=True, verbose_name='仅工作日')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '提醒规则',
                'verbose_name_plural': '提醒规则',
                'ordering': ['project', 'role', 'cutoff_time'],
                'unique_together': {('project', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ReportMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, null=True, verbose_name='角色')),
                ('date', models.DateField(verbose_name='缺报日期')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='补报时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_misses', to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_misses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '缺报记录',
                'verbose_name_plural': '缺报记录',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='work_logs_r_date_cc72c3_idx'), models.Index(fields=['user', 'date'], name='work_logs_r_user_id_337b1b_idx')],
                'unique_together': {('user', 'project', 'role', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReportTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('role', models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, null=True, verbose_name='适用角色')),
                ('content', models.TextField(blank=True, verbose_name='模板内容')),
                ('placeholders', models.JSONField(blank=True, default=dict, verbose_name='占位符')),
                ('is_shared', models.BooleanField(default=True, verbose_name='是否共享')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='projects.project', verbose_name='适用项目')),
            ],
            options={
                'verbose_name': '日报模板版本',
                'verbose_name_plural': '日报模板版本',
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'project', 'role', 'version')},
            },
        ),
    ]
