# Generated by Django 5.2.8 on 2026-02-28 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('status', models.CharField(choices=[('present', '出勤 / Present'), ('absent', '缺勤 / Absent'), ('leave', '请假 / Leave'), ('makeup', '补卡 / Make-up')], default='present', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_record', to='work_logs.dailyreport', verbose_name='关联日报')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='work_logs_a_user_id_df9fba_idx'), models.Index(fields=['date'], name='work_logs_a_date_b727d7_idx'), models.Index(fields=['status'], name='work_logs_a_status_b5952a_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
