# Generated by Django 5.2.8 on 2026-06-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_projects_pr_name_e0a39f_idx_projects_pr_name_11d782_idx_and_more'),
        ('work_logs', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderrule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='projects.project', verbose_name='项目'),
        ),
    ]
