# Generated by Django 5.2.8 on 2026-06-19 17:02

from django.db import migrations, models


CONTENT_FIELDS = (
    'today_work',
    'progress_issues',
    'tomorrow_plan',
    'testing_scope',
    'testing_progress',
    'bug_summary',
    'testing_tomorrow',
    'product_today',
    'product_coordination',
    'product_tomorrow',
    'ui_today',
    'ui_feedback',
    'ui_tomorrow',
    'ops_today',
    'ops_monitoring',
    'ops_tomorrow',
    'mgr_progress',
    'mgr_risks',
    'mgr_tomorrow',
)
LEGACY_FIELDS = CONTENT_FIELDS + ('project',)


def move_content_to_json(apps, schema_editor):
    DailyReport = apps.get_model('work_logs', 'DailyReport')
    manager = DailyReport.objects.using(schema_editor.connection.alias)
    batch = []
    for report in manager.all().iterator(chunk_size=500):
        content = dict(report.content or {})
        for field_name in CONTENT_FIELDS:
            value = getattr(report, field_name)
            if value not in (None, ''):
                content[field_name] = value
        if report.project:
            content['_legacy_project'] = report.project
        report.content = content
        batch.append(report)
        if len(batch) == 500:
            manager.bulk_update(batch, ['content'], batch_size=500)
            batch = []
    if batch:
        manager.bulk_update(batch, ['content'], batch_size=500)


def restore_content_columns(apps, schema_editor):
    DailyReport = apps.get_model('work_logs', 'DailyReport')
    manager = DailyReport.objects.using(schema_editor.connection.alias)
    batch = []
    for report in manager.all().iterator(chunk_size=500):
        content = report.content or {}
        for field_name in CONTENT_FIELDS:
            setattr(report, field_name, content.get(field_name, ''))
        report.project = content.get('_legacy_project', '')
        batch.append(report)
        if len(batch) == 500:
            manager.bulk_update(batch, LEGACY_FIELDS, batch_size=500)
            batch = []
    if batch:
        manager.bulk_update(batch, LEGACY_FIELDS, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('work_logs', '0003_alter_reminderrule_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='content',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化日报内容'),
        ),
        migrations.RunPython(move_content_to_json, restore_content_columns),
        migrations.RemoveField(
            model_name='dailyreport',
            name='bug_summary',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='mgr_progress',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='mgr_risks',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='mgr_tomorrow',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='ops_monitoring',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='ops_today',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='ops_tomorrow',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='product_coordination',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='product_today',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='product_tomorrow',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='progress_issues',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='project',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='testing_progress',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='testing_scope',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='testing_tomorrow',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='today_work',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='tomorrow_plan',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='ui_feedback',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='ui_today',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='ui_tomorrow',
        ),
    ]
