# Generated by Django 5.2.8 on 2025-11-25 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], default='dev', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('today_work', models.TextField(blank=True)),
                ('progress_issues', models.TextField(blank=True)),
                ('tomorrow_plan', models.TextField(blank=True)),
                ('testing_scope', models.TextField(blank=True)),
                ('testing_progress', models.TextField(blank=True)),
                ('bug_summary', models.TextField(blank=True)),
                ('testing_tomorrow', models.TextField(blank=True)),
                ('product_today', models.TextField(blank=True)),
                ('product_coordination', models.TextField(blank=True)),
                ('product_tomorrow', models.TextField(blank=True)),
                ('ui_today', models.TextField(blank=True)),
                ('ui_feedback', models.TextField(blank=True)),
                ('ui_tomorrow', models.TextField(blank=True)),
                ('ops_today', models.TextField(blank=True)),
                ('ops_monitoring', models.TextField(blank=True)),
                ('ops_tomorrow', models.TextField(blank=True)),
                ('mgr_progress', models.TextField(blank=True)),
                ('mgr_risks', models.TextField(blank=True)),
                ('mgr_tomorrow', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date', 'role')},
            },
        ),
    ]
