# Generated by Django 4.2.23 on 2025-12-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['status'], name='reports_dai_status_2ecc8c_idx'),
        ),
    ]
