# Generated by Django 5.2.8 on 2026-01-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_projectphaseconfig_project_overall_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '高 / High'), ('medium', '中 / Medium'), ('low', '低 / Low')], default='medium', max_length=20),
        ),
    ]
