# Generated by Django 5.2.8 on 2026-01-25 16:17

import datetime
import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_notification_permissionmatrix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='PermissionMatrix',
        ),
        migrations.AlterUniqueTogether(
            name='projectmemberpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectmemberpermission',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='projectmemberpermission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmemberpermission',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': '审计日志', 'verbose_name_plural': '审计日志'},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '日报', 'verbose_name_plural': '日报'},
        ),
        migrations.AlterModelOptions(
            name='exportjob',
            options={'ordering': ['-created_at'], 'verbose_name': '导出任务', 'verbose_name_plural': '导出任务'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='projectphasechangelog',
            options={'ordering': ['-changed_at'], 'verbose_name': '项目阶段变更日志', 'verbose_name_plural': '项目阶段变更日志'},
        ),
        migrations.AlterModelOptions(
            name='projectphaseconfig',
            options={'ordering': ['order_index'], 'verbose_name': '项目阶段配置', 'verbose_name_plural': '项目阶段配置'},
        ),
        migrations.AlterModelOptions(
            name='reminderrule',
            options={'ordering': ['project', 'role', 'cutoff_time'], 'verbose_name': '提醒规则', 'verbose_name_plural': '提醒规则'},
        ),
        migrations.AlterModelOptions(
            name='reportmiss',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '缺报记录', 'verbose_name_plural': '缺报记录'},
        ),
        migrations.AlterModelOptions(
            name='reporttemplateversion',
            options={'ordering': ['name', '-version'], 'verbose_name': '日报模板版本', 'verbose_name_plural': '日报模板版本'},
        ),
        migrations.AlterModelOptions(
            name='roletemplate',
            options={'ordering': ['sort_order', 'role'], 'verbose_name': '角色模板', 'verbose_name_plural': '角色模板'},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['key'], 'verbose_name': '系统设置', 'verbose_name_plural': '系统设置'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterModelOptions(
            name='taskattachment',
            options={'ordering': ['-created_at'], 'verbose_name': '任务附件', 'verbose_name_plural': '任务附件'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['-created_at'], 'verbose_name': '任务评论', 'verbose_name_plural': '任务评论'},
        ),
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-created_at'], 'verbose_name': '任务变更历史', 'verbose_name_plural': '任务变更历史'},
        ),
        migrations.AlterModelOptions(
            name='taskslatimer',
            options={'ordering': ['-created_at'], 'verbose_name': 'SLA计时器', 'verbose_name_plural': 'SLA计时器'},
        ),
        migrations.AlterModelOptions(
            name='tasktemplateversion',
            options={'ordering': ['name', '-version'], 'verbose_name': '任务模板版本', 'verbose_name_plural': '任务模板版本'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': '用户偏好', 'verbose_name_plural': '用户偏好'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('export', '导出'), ('delete', '删除'), ('create', '创建'), ('update', '更新'), ('access', '访问')], max_length=20, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='数据快照'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='extra',
            field=models.TextField(blank=True, verbose_name='额外信息'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='method',
            field=models.CharField(max_length=10, verbose_name='方法'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.CharField(max_length=255, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='bug_summary',
            field=models.TextField(blank=True, verbose_name='缺陷汇总'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='mgr_progress',
            field=models.TextField(blank=True, verbose_name='整体进度'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='mgr_risks',
            field=models.TextField(blank=True, verbose_name='风险管理'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='mgr_tomorrow',
            field=models.TextField(blank=True, verbose_name='明日管理计划'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='ops_monitoring',
            field=models.TextField(blank=True, verbose_name='监控状况'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='ops_today',
            field=models.TextField(blank=True, verbose_name='今日运维工作'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='ops_tomorrow',
            field=models.TextField(blank=True, verbose_name='明日运维计划'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='product_coordination',
            field=models.TextField(blank=True, verbose_name='协调事项'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='product_today',
            field=models.TextField(blank=True, verbose_name='今日产品工作'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='product_tomorrow',
            field=models.TextField(blank=True, verbose_name='明日产品计划'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='progress_issues',
            field=models.TextField(blank=True, verbose_name='进度与问题'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='project',
            field=models.CharField(blank=True, max_length=200, verbose_name='主项目(旧)'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='reports', to='reports.project', verbose_name='关联项目'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='role',
            field=models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('draft', '草稿 / Draft'), ('submitted', '已提交 / Submitted')], default='submitted', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='testing_progress',
            field=models.TextField(blank=True, verbose_name='测试进度'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='testing_scope',
            field=models.TextField(blank=True, verbose_name='测试范围'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='testing_tomorrow',
            field=models.TextField(blank=True, verbose_name='明日测试计划'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='today_work',
            field=models.TextField(blank=True, verbose_name='今日工作'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='tomorrow_plan',
            field=models.TextField(blank=True, verbose_name='明日计划'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='ui_feedback',
            field=models.TextField(blank=True, verbose_name='反馈修改'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='ui_today',
            field=models.TextField(blank=True, verbose_name='今日设计工作'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='ui_tomorrow',
            field=models.TextField(blank=True, verbose_name='明日设计计划'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='expires_at',
            field=models.DateTimeField(default=reports.models.default_export_expiry, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='export_type',
            field=models.CharField(max_length=50, verbose_name='导出类型'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='message',
            field=models.TextField(blank=True, verbose_name='消息'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='进度(%)'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('pending', '待处理 / Pending'), ('running', '处理中 / Running'), ('done', '完成 / Done'), ('failed', '失败 / Failed')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], default='dev', max_length=10, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='项目代号'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='reports.projectphaseconfig', verbose_name='当前阶段'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='overall_progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='总体进度(%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sla_hours',
            field=models.PositiveIntegerField(blank=True, help_text='项目级 SLA 提醒窗口（小时）', null=True, verbose_name='SLA时限(小时)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='projectphasechangelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='变更时间'),
        ),
        migrations.AlterField(
            model_name='projectphasechangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='变更人'),
        ),
        migrations.AlterField(
            model_name='projectphasechangelog',
            name='new_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_as_new', to='reports.projectphaseconfig', verbose_name='新阶段'),
        ),
        migrations.AlterField(
            model_name='projectphasechangelog',
            name='old_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_as_old', to='reports.projectphaseconfig', verbose_name='原阶段'),
        ),
        migrations.AlterField(
            model_name='projectphasechangelog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_logs', to='reports.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectphaseconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='projectphaseconfig',
            name='order_index',
            field=models.PositiveIntegerField(default=0, verbose_name='排序索引'),
        ),
        migrations.AlterField(
            model_name='projectphaseconfig',
            name='phase_name',
            field=models.CharField(max_length=50, verbose_name='阶段名称'),
        ),
        migrations.AlterField(
            model_name='projectphaseconfig',
            name='progress_percentage',
            field=models.PositiveIntegerField(help_text='0-100', verbose_name='进度百分比'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='channel',
            field=models.CharField(default='email', max_length=50, verbose_name='通知渠道'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='cutoff_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='reports.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='role',
            field=models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], help_text='为空则对项目内全部角色生效', max_length=10, null=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='reminderrule',
            name='weekdays_only',
            field=models.BooleanField(default=True, verbose_name='仅工作日'),
        ),
        migrations.AlterField(
            model_name='reportmiss',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间'),
        ),
        migrations.AlterField(
            model_name='reportmiss',
            name='date',
            field=models.DateField(verbose_name='缺报日期'),
        ),
        migrations.AlterField(
            model_name='reportmiss',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='通知时间'),
        ),
        migrations.AlterField(
            model_name='reportmiss',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_misses', to='reports.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='reportmiss',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='补报时间'),
        ),
        migrations.AlterField(
            model_name='reportmiss',
            name='role',
            field=models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, null=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='reportmiss',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_misses', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='content',
            field=models.TextField(blank=True, verbose_name='模板内容'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='is_shared',
            field=models.BooleanField(default=True, verbose_name='是否共享'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='name',
            field=models.CharField(max_length=200, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict, verbose_name='占位符'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='reports.project', verbose_name='适用项目'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='role',
            field=models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, null=True, verbose_name='适用角色'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='使用次数'),
        ),
        migrations.AlterField(
            model_name='reporttemplateversion',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='hint',
            field=models.TextField(blank=True, verbose_name='提示语'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict, verbose_name='占位符配置'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='role',
            field=models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, unique=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='sample_md',
            field=models.TextField(blank=True, help_text='示例 Markdown，填写页可一键套用', verbose_name='示例内容'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='键'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.CharField(blank=True, max_length=200, verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='task',
            name='amber_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='即将逾期通知时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='逾期通知时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '高 / High'), ('medium', '中 / Medium'), ('low', '低 / Low')], default='medium', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reports.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='task',
            name='red_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='紧急通知时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '未开始 / Pending'), ('in_progress', '进行中 / In Progress'), ('on_hold', '挂起 / On Hold'), ('completed', '已完成 / Completed'), ('overdue', '逾期 / Overdue'), ('reopened', '重新打开 / Reopened')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.task', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='url',
            field=models.URLField(blank=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='mentions',
            field=models.JSONField(blank=True, default=list, verbose_name='提及用户'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.task', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='field',
            field=models.CharField(max_length=50, verbose_name='变更字段'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='new_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='新值'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='old_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='旧值'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reports.task', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='taskslatimer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='taskslatimer',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='暂停时间'),
        ),
        migrations.AlterField(
            model_name='taskslatimer',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_timer', to='reports.task', verbose_name='任务'),
        ),
        migrations.AlterField(
            model_name='taskslatimer',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='累计暂停秒数'),
        ),
        migrations.AlterField(
            model_name='taskslatimer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='content',
            field=models.TextField(blank=True, verbose_name='任务内容'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='is_shared',
            field=models.BooleanField(default=True, verbose_name='是否共享'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='name',
            field=models.CharField(max_length=200, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='reports.project', verbose_name='适用项目'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='role',
            field=models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, null=True, verbose_name='适用角色'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='任务标题'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='url',
            field=models.URLField(blank=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='使用次数'),
        ),
        migrations.AlterField(
            model_name='tasktemplateversion',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='偏好数据'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ProjectMemberPermission',
        ),
    ]
