# Generated by Django 5.2.8 on 2025-11-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
