# Generated by Django 5.2.8 on 2026-01-25 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_notification_permissionmatrix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_attachments/', verbose_name='文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.project', verbose_name='项目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_project_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '项目附件',
                'verbose_name_plural': '项目附件',
                'ordering': ['-created_at'],
            },
        ),
    ]
