# Generated by Django 4.2.23 on 2025-11-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_task_status_taskattachment_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, unique=True)),
                ('hint', models.TextField(blank=True)),
                ('placeholders', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '未开始 / Pending'), ('in_progress', '进行中 / In Progress'), ('on_hold', '挂起 / On Hold'), ('completed', '已完成 / Completed'), ('overdue', '逾期 / Overdue'), ('reopened', '重新打开 / Reopened')], default='pending', max_length=20),
        ),
    ]
