# Generated by Django 4.2.23 on 2025-11-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_roletemplate_alter_task_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'date'], name='reports_dai_user_id_f71a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'status'], name='reports_dai_user_id_c88740_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['role', 'date'], name='reports_dai_role_b09eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='reports_tas_status_a68b36_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='reports_tas_project_9d0c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='reports_tas_user_id_e1d2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at'], name='reports_tas_due_at_c79839_idx'),
        ),
    ]
