# Generated by Django 5.2.8 on 2026-01-26 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_task_collaborators_alter_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='reports_pro_is_acti_42cb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='reports_pro_code_ff14e6_idx'),
        ),
    ]
