# Generated by Django 5.2.8 on 2026-01-26 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_project_reports_pro_is_acti_42cb1c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='变更详情'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='实体ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='实体类型'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='operator_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='操作人姓名'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('export', '导出'), ('delete', '删除'), ('create', '创建'), ('update', '更新'), ('access', '访问'), ('other', '其他')], max_length=20, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=10, verbose_name='方法'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, max_length=255, verbose_name='路径'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='reports_aud_entity__98d39b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='reports_aud_action_c56ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='reports_aud_created_f36188_idx'),
        ),
    ]
