# Generated by Django 4.2.23 on 2025-11-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_dailyreport_reports_dai_user_id_f71a4b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='mentions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
