# Generated by Django 4.2.23 on 2025-11-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_taskattachment_file_taskcomment_mentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
