# Generated by Django 5.2.8 on 2026-01-26 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auditlog_changes_auditlog_entity_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='reports.project', verbose_name='关联项目'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['project'], name='reports_aud_project_52fd1d_idx'),
        ),
    ]
