# Generated by Django 5.2.8 on 2026-01-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auditlog_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='reports.task', verbose_name='关联任务'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['task'], name='reports_aud_task_id_d73241_idx'),
        ),
    ]
