# Generated by Django 4.2.23 on 2025-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sla_hours',
            field=models.PositiveIntegerField(blank=True, help_text='项目级 SLA 提醒窗口（小时）', null=True),
        ),
    ]
