# Generated by Django 5.2.8 on 2026-01-27 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_notification_expires_at_notification_is_pushed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='reports_aud_entity__98d39b_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='data',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='path',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='remarks',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='详情'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='result',
            field=models.CharField(choices=[('success', '成功 / Success'), ('failure', '失败 / Failure')], default='success', max_length=10, verbose_name='结果'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='summary',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='对象ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='对象名称'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='对象类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', '登录 / Login'), ('logout', '登出 / Logout'), ('create', '创建 / Create'), ('update', '更新 / Update'), ('delete', '删除 / Delete'), ('access', '访问 / Access'), ('export', '导出 / Export'), ('upload', '上传 / Upload'), ('other', '其他 / Other')], max_length=20, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', '待处理 / To Do'), ('in_progress', '进行中 / In Progress'), ('blocked', '阻塞中 / Blocked'), ('in_review', '待评审 / In Review'), ('done', '已完成 / Done'), ('closed', '已关闭 / Closed')], default='todo', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='reports_aud_target__aebc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['result'], name='reports_aud_result_ad1ee3_idx'),
        ),
    ]
