# Generated by Django 4.2.23 on 2025-11-29 04:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0014_taskhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roletemplate',
            options={'ordering': ['sort_order', 'role']},
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='sample_md',
            field=models.TextField(blank=True, help_text='示例 Markdown，填写页可一键套用'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskSlaTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('total_paused_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_timer', to='reports.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, null=True)),
                ('date', models.DateField()),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_misses', to='reports.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_misses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='reports_rep_date_e070b3_idx'), models.Index(fields=['user', 'date'], name='reports_rep_user_id_64adf2_idx')],
                'unique_together': {('user', 'project', 'role', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], help_text='为空则对项目内全部角色生效', max_length=10, null=True)),
                ('cutoff_time', models.TimeField(default=datetime.time(20, 0))),
                ('channel', models.CharField(default='email', max_length=50)),
                ('weekdays_only', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='reports.project')),
            ],
            options={
                'ordering': ['project', 'role', 'cutoff_time'],
                'unique_together': {('project', 'role')},
            },
        ),
    ]
