# Generated by Django 5.2.8 on 2026-01-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_remove_auditlog_reports_aud_entity__98d39b_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='projectmemberpermission',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='reminderrule',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='reportmiss',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplateversion',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='tasktemplateversion',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='PermissionMatrix',
        ),
        migrations.DeleteModel(
            name='RoleTemplate',
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='ExportJob',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ReminderRule',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectAttachment',
        ),
        migrations.DeleteModel(
            name='ProjectMemberPermission',
        ),
        migrations.DeleteModel(
            name='ProjectPhaseChangeLog',
        ),
        migrations.DeleteModel(
            name='ProjectPhaseConfig',
        ),
        migrations.DeleteModel(
            name='ReportMiss',
        ),
        migrations.DeleteModel(
            name='ReportTemplateVersion',
        ),
        migrations.DeleteModel(
            name='TaskSlaTimer',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
        migrations.DeleteModel(
            name='TaskHistory',
        ),
        migrations.DeleteModel(
            name='TaskTemplateVersion',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
