# Generated by Django 5.2.8 on 2026-01-30 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='变更字段')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='旧值')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='新值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tasks.task', verbose_name='任务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '任务变更历史',
                'verbose_name_plural': '任务变更历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, max_length=150, verbose_name='操作人姓名')),
                ('action', models.CharField(choices=[('login', '登录 / Login'), ('logout', '登出 / Logout'), ('create', '创建 / Create'), ('update', '更新 / Update'), ('delete', '删除 / Delete'), ('access', '访问 / Access'), ('export', '导出 / Export'), ('upload', '上传 / Upload'), ('other', '其他 / Other')], max_length=20, verbose_name='动作')),
                ('result', models.CharField(choices=[('success', '成功 / Success'), ('failure', '失败 / Failure')], default='success', max_length=10, verbose_name='结果')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='对象ID')),
                ('target_label', models.CharField(blank=True, max_length=255, verbose_name='对象名称')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='projects.project', verbose_name='关联项目')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tasks.task', verbose_name='关联任务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['result'], name='audit_audit_result_4e9791_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'), models.Index(fields=['project'], name='audit_audit_project_7b59cc_idx'), models.Index(fields=['task'], name='audit_audit_task_id_922e08_idx')],
            },
        ),
    ]
