# Generated by Django 5.2.8 on 2026-01-28 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tasks', '0002_alter_task_collaborators_alter_task_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='变更字段')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='旧值')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='新值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tasks.task', verbose_name='任务')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '任务变更历史',
                'verbose_name_plural': '任务变更历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
