# Generated by Django 5.2.8 on 2026-02-14 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('category', models.CharField(choices=[('TASK', '任务-TASK'), ('BUG', '缺陷-BUG')], default='TASK', max_length=20, verbose_name='分类')),
                ('status', models.CharField(choices=[('todo', '待处理 / To Do'), ('in_progress', '进行中 / In Progress'), ('blocked', '阻塞中 / Blocked'), ('in_review', '待评审 / In Review'), ('done', '已完成 / Done'), ('closed', '已关闭 / Closed'), ('new', '新建 / New'), ('confirmed', '已确认缺陷 / Confirmed'), ('fixing', '修复中 / In Progress'), ('verifying', '验证中 / Verifying')], default='todo', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('high', '高 / High'), ('medium', '中 / Medium'), ('low', '低 / Low')], default='medium', max_length=20, verbose_name='优先级')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='逾期通知时间')),
                ('amber_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='即将逾期通知时间')),
                ('red_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='紧急通知时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='协作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='主负责人')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('file', models.FileField(blank=True, null=True, upload_to='task_attachments/', verbose_name='文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('mentions', models.JSONField(blank=True, default=list, verbose_name='提及用户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务评论',
                'verbose_name_plural': '任务评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSlaTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='暂停时间')),
                ('total_paused_seconds', models.PositiveIntegerField(default=0, verbose_name='累计暂停秒数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_timer', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': 'SLA计时器',
                'verbose_name_plural': 'SLA计时器',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('role', models.CharField(blank=True, choices=[('dev', '开发 / Developer'), ('qa', '测试 / QA'), ('pm', '产品 / Product Manager'), ('ui', '设计 / UI / UX'), ('ops', '运维 / Ops'), ('mgr', '项目管理 / PM / PMO')], max_length=10, null=True, verbose_name='适用角色')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('content', models.TextField(blank=True, verbose_name='任务内容')),
                ('url', models.URLField(blank=True, verbose_name='链接')),
                ('is_shared', models.BooleanField(default=True, verbose_name='是否共享')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='projects.project', verbose_name='适用项目')),
            ],
            options={
                'verbose_name': '任务模板版本',
                'verbose_name_plural': '任务模板版本',
                'ordering': ['name', '-version'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='tasks_task_categor_521417_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_task_project_b78682_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='tasks_task_user_id_c0fce1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='tasks_task_project_4035b9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='tasks_task_user_id_0b1849_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_task_created_be1ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at'], name='tasks_task_due_at_59a3cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktemplateversion',
            unique_together={('name', 'project', 'role', 'version')},
        ),
    ]
