# Generated by Django 5.2.8 on 2026-02-04 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='待办事项')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('priority', models.CharField(choices=[('high', '高 / High'), ('medium', '中 / Medium'), ('low', '低 / Low')], default='medium', max_length=20, verbose_name='优先级')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='排序位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_todos', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人待办',
                'verbose_name_plural': '个人待办',
                'ordering': ['position', '-created_at'],
                'indexes': [models.Index(fields=['user', 'position'], name='tasks_perso_user_id_3c28c4_idx'), models.Index(fields=['user', 'is_completed'], name='tasks_perso_user_id_8747fa_idx')],
            },
        ),
    ]
