# Generated by Django 5.2.8 on 2026-03-01 08:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskattachment_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed_at'], name='tasks_task_complete_idx'),
        ),
    ]
