# Generated by Django 5.2.8 on 2026-01-30 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_managers_alter_project_members_and_more'),
        ('tasks', '0002_alter_task_collaborators_alter_task_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('TASK', '任务-TASK'), ('BUG', '缺陷-BUG')], default='TASK', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', '待处理 / To Do'), ('in_progress', '进行中 / In Progress'), ('blocked', '阻塞中 / Blocked'), ('in_review', '待评审 / In Review'), ('done', '已完成 / Done'), ('closed', '已关闭 / Closed'), ('new', '新建 / New'), ('confirmed', '已确认缺陷 / Confirmed'), ('fixing', '修复中 / In Progress'), ('verifying', '验证中 / Verifying')], default='todo', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='tasks_task_categor_521417_idx'),
        ),
    ]
