# Generated by Django 5.2.8 on 2026-06-19 16:02

from django.conf import settings
from django.db import migrations, models


TASKCOMMENT_INDEXES = (
    models.Index(fields=['task'], name='tasks_taskc_task_id_8332b2_idx'),
    models.Index(fields=['created_at'], name='tasks_taskc_created_23e5ec_idx'),
)


def create_missing_taskcomment_indexes(apps, schema_editor):
    TaskComment = apps.get_model('tasks', 'TaskComment')
    table_name = TaskComment._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        existing = schema_editor.connection.introspection.get_constraints(cursor, table_name)

    for index in TASKCOMMENT_INDEXES:
        if index.name not in existing:
            schema_editor.add_index(TaskComment, index)


def drop_taskcomment_indexes(apps, schema_editor):
    TaskComment = apps.get_model('tasks', 'TaskComment')
    table_name = TaskComment._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        existing = schema_editor.connection.introspection.get_constraints(cursor, table_name)

    for index in reversed(TASKCOMMENT_INDEXES):
        if index.name in existing:
            schema_editor.remove_index(TaskComment, index)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_task_completed_at_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_missing_taskcomment_indexes,
                    reverse_code=drop_taskcomment_indexes,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='taskcomment',
                    index=TASKCOMMENT_INDEXES[0],
                ),
                migrations.AddIndex(
                    model_name='taskcomment',
                    index=TASKCOMMENT_INDEXES[1],
                ),
            ],
        ),
    ]
