# Generated by Django 5.2.8 on 2026-06-19 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_task_completed_at_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task'], name='tasks_taskc_task_id_8332b2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['created_at'], name='tasks_taskc_created_23e5ec_idx'),
        ),
    ]
